### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by feynmam** [swuecho/chat#108]
昨天更新后一直是404 page not found，5.0到5.3

**Comment by swuecho** [comment]
https://github.com/swuecho/chat/releases/tag/v0.5.0

5.0 精简了 docker-compose 你贴一下docker-compose.yaml

**Comment by swuecho** [comment]
这种改动会造成麻烦, 不过问题不大, 应该可以找到问题.

**Comment by feynmam** [comment]
docker-compose.yaml只改了api，两个vps上都404，很奇怪

**Comment by swuecho** [comment]
最新的docker-compose.yaml 应该是这样的


https://github.com/swuecho/chat/blob/v0.5.5/docker-compose.yaml
