### ISSUE TITLE
create chat snapshot and make the conversation sharable

### ISSUE THREAD

**Issue by swuecho** [swuecho/chat#129]
```
-- for share chat feature
CREATE TABLE IF NOT EXISTS chat_snapshot (
    id SERIAL PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL default '',
    user_id INTEGER NOT NULL default 0,
    title VARCHAR(255) NOT NULL default '',
    summary TEXT NOT NULL default '',
    tags JSONB DEFAULT '{}' NOT NULL,
    conversation JSONB NOT NULL default '{}',
    created_at TIMESTAMP DEFAULT now() NOT NULL
);
```

**Comment by swuecho** [comment]
https://github.com/Chanzhaoyu/chatgpt-web/issues/1456

**Comment by swuecho** [comment]
可以用了, 但是还不能share, 必须才能看自己的.

**Comment by swuecho** [comment]
@shuaiplus  基本功能做好了 你可以去登录demo 账号  https://github.com/swuecho/chat/discussions/102  看一下哪里需要改进.

你也可以注册个号, 我给你加一点ratelimit

**Comment by shuaiplus** [comment]
> @shuaiplus 基本功能做好了 你可以去登录demo 账号 #102 看一下哪里需要改进.
> 
> 你也可以注册个号, 我给你加一点ratelimit

2327005759@qq.com  
如果你加上去的是这个，好像没有正式对话就点不了，你给个权限，我试试：
![image](https://user-images.githubusercontent.com/100134295/232782086-f60a043f-71c2-4c9a-9061-e76c2aa252b3.png)

**Comment by swuecho** [comment]
已经加了 20个对话/10分钟 正常使用应该是够了.

**Comment by shuaiplus** [comment]
牛的，没发现bug
