### ISSUE TITLE
普通用户也可打开管理后台，并修改”模型“页下的配置

### ISSUE THREAD

**Issue by STillSB** [swuecho/chat#151]
1、发现普通用户也可打开"管理后台"并在“模型”页做出修改
2、”限流“页是正常的，会弹出”非管理员禁止访问“
3、希望普通用户直接在界面上直接显示”管理后台“入口按钮
![image](https://user-images.githubusercontent.com/7955804/233010551-eb84553e-59e3-4862-8110-bd929abddda5.png)

**Comment by swuecho** [comment]
> 发现普通用户也可打开"管理后台"并在“模型”页做出修改

多谢反馈, 这个我也发现了, 好在正式的模型(chatgpt, claude)还是写死的. 并没有用数据库中的数据. 

3. 是希望**管理员**直接显示管理按钮吧?

**Comment by swuecho** [comment]
https://github.com/swuecho/chat/issues/136 对于3, 当时这么想的, 后来懒省事, 没改.

**Comment by swuecho** [comment]
发现普通用户也可打开"管理后台"并在“模型”页做出修改

考虑过让系统做的易于扩展, 

管理员添加的模型是全局的, 用户添加的模型自己能用. 但是用户添加模型的地方肯定不在管理页面, 我限制一下.

**Comment by swuecho** [comment]
https://github.com/swuecho/chat/pull/153

**Comment by swuecho** [comment]
https://github.com/swuecho/chat/pull/152
