### ISSUE TITLE
注册流程问题

### ISSUE THREAD

**Issue by ywgx** [swuecho/chat#222]
虽然项目是面向团队内部, 但是邮箱注册流程感觉还是需要合理一点

注册--> 邮件发送激活链接 --> 点击激活  --> 创建用户 类似这个 https://intio.org

**Comment by swuecho** [comment]
这个需要配email发送相关链接

现在就是直接注册 然后找管理员加ratelimit  一般几十人的用户够了

确实不是最优  有时间优化 或者有人有空优化的话  只要能走通 我乐意接受pr

**Comment by swuecho** [comment]
如果在内网, 把openai_ratelimit=xx 默认值弄大一点, 也不需要介入.

就是找密码比较麻烦. (重新注册一个就好了)
