### ISSUE TITLE
Save the configuration to the database and use the last configuration for a new session

### ISSUE THREAD

**Issue by oneisall8955** [swuecho/chat#284]
![image](https://user-images.githubusercontent.com/44989283/235655879-bdf04728-e3de-4a11-81c8-3960cf96b822.png)

- 如上图，调整的参数存到数据库，后续新开的对话沿用上次调整的配置进行会话
- 参数值建议 https://github.com/Yidadaa/ChatGPT-Next-Web 这种形式可以填写而不仅仅是拉动调整，（有些配置数值拉动的最大值太小了）

**Comment by swuecho** [comment]
1 默认用之前的配置 这个我有时候也会觉得需要 也可能是默认值不够好的问题

你常用的默认值是什么

2. 默认值小了 有些是我故意的 因为有用到gpt4的功能 不想让用户弄过大的值

**Comment by swuecho** [comment]
https://github.com/swuecho/chat/pull/286

**Comment by swuecho** [comment]
```
const tokenUpperLimit = computed(() => {
  const discount_ratio = 0.8
  if (modelRef.value.chatModel === 'gpt-4')
    return Math.floor(1024 * 8 * discount_ratio)
  else if (modelRef.value.chatModel === 'gpt-4-32k')
    return Math.floor(32 * 1024 * discount_ratio)
  else if (modelRef.value.chatModel === 'text-davinci-003')
    return Math.floor(4 * 1024 * discount_ratio)
  else
    return Math.floor(1024 * 2 * discount_ratio)
})
```

我在官方能查到的最大值上加个一个ratio 0.8, 考虑到问题一般比回答短. 

感觉针对2 这样并无太大问题. 可以在model 设置上 加个 最大token, 目前不是很有必要?

**Comment by swuecho** [comment]
<img width="1868" alt="image" src="https://user-images.githubusercontent.com/666683/235675225-c45378bb-1391-41e2-8d0d-9efea33fddce.png">

- [ ] 就是在这个表加上一列, 最大token, 然后前端拿到去显示上线

**Comment by oneisall8955** [comment]
![image](https://user-images.githubusercontent.com/44989283/235681373-0a4fc728-fe89-41b6-80af-05e6a991e356.png)

https://github.com/Yidadaa/ChatGPT-Next-Web  我在用这个项目的默认值，感觉挺好，另外有压缩历史记录和摘要功能，不清楚怎么做到的

**Comment by swuecho** [comment]
就是上下文数量不一致 10 vs 4, 别的我看没区别. 
https://github.com/swuecho/chat/pull/288


- [ ] 压缩上下文摘要

**Comment by swuecho** [comment]
https://github.com/swuecho/chat/pull/294

想了一下那个discount ratio 应该在后端, 后端已经用了2/3, 这边没必要了.
