### ISSUE TITLE
Keep up with original project features(chatgpt-web)

### ISSUE THREAD

**Issue by oneisall8955** [swuecho/chat#285]
原前端项目 https://github.com/Chanzhaoyu/chatgpt-web 增加 / 键的快捷Prompt 扮演角色功能，希望迁移到当前项目

**Comment by swuecho** [comment]
https://github.com/Chanzhaoyu/chatgpt-web/pull/268

**Comment by swuecho** [comment]
@oneisall8955 你如果有时间可以试试, 就是把上面的pr里面的文件copy过来.

需要注意的是, 这边第一个消息是prompt, 别的应该没啥问题.

**Comment by swuecho** [comment]
> @swuecho 好的，估计得下周才有时间

这个我明天抽空做 如果你还没有做的话

**Comment by swuecho** [comment]
> 需要注意的是, 这边第一个消息是prompt, 别的应该没啥问题.

这个完美契合我这边的思路, 原封不动的copy过来就能用.

**Comment by swuecho** [comment]
DONE
