### ISSUE TITLE
为什么要将回复的string限制在200，有什么特殊考虑吗？

### ISSUE THREAD

**Issue by oldwang12** [swuecho/chat#364]
#### 故障描述：
  chatgpt在页面上回复的时候，如果回复内容大于一定的长度，暂时就不再回复了。

#### 原因：
后端 在 [这里](https://github.com/swuecho/chat/blob/master/api/chat_main_handler.go#L419) 指定了回复内容长度
这会导致前端无法获取到后端的响应而等待。

**Comment by oldwang12** [comment]
@swuecho

**Comment by swuecho** [comment]
这个代码是没问题的， 200 字以内有打字机效果。

整体的内容EOF 之后会发。 如果你文字断了， 应该是别的问题。

**Comment by swuecho** [comment]
https://github.com/swuecho/chat/blob/829e214088cd0f09ceb3d7af497d3f31a9cc2a71/api/chat_main_handler.go#L386C4-L392C5

**Comment by swuecho** [comment]
你找一个可用复现的例子， 我看看怎么回事。

**Comment by oldwang12** [comment]
> 你找一个可用复现的例子， 我看看怎么回事。

目前我线上使用的是去掉了200字数的限制，现在消息是ok的。

**Comment by oldwang12** [comment]
线上地址： caiplus.pro

**Comment by swuecho** [comment]
> > 你找一个可用复现的例子， 我看看怎么回事。
> 
> 为什么200字之后要按行推送呢，作为一个用户来说，是不是打印机形式更好。
> 
> 目前我线上使用的是去掉了200字数的限制，现在消息是ok的。

费流量。。。200字以后按照行来更新的。 这个看需求。

**Comment by swuecho** [comment]
你可以加个环境变量处理一下 默认是不开启 有兴趣可以弄个pr

**Comment by oldwang12** [comment]
okk

**Comment by oldwang12** [comment]
> 你可以加个环境变量处理一下 默认是不开启 有兴趣可以弄个pr

https://github.com/swuecho/chat/pull/365/commits
