### ISSUE TITLE
接入langchain功能分析

### ISSUE THREAD

**Issue by coljiang** [swuecho/chat#385]
目标  : 在项目中接入langchian实现结合文档与提问回复问题
详细文档
https://xuouatsmvp.feishu.cn/docx/LniNdszXMo9ExNxCqztc1DXxnRe

**Comment by swuecho** [comment]
pgvector: https://supabase.com/blog/openai-embeddings-postgres-vector

**Comment by swuecho** [comment]
![image](https://github.com/swuecho/chat/assets/666683/e30e3cb4-1f59-4431-9885-32e98b324fa7)
OpenAI已经更新了他们的微调功能，提供了一个直观的用户界面，使用户能够在不编写任何代码的情况下进行模型的微调。

https://twitter.com/GPTDAOCN/status/1710711450111791199

**Comment by swuecho** [comment]
已经实现了文件上传, 如果模型支持图片, 音视频, 则附上.

文本则直接嵌入对话.

没有RAG, 这样会导致token 用量多, 但是简单. RAG 还是复杂了.
