### ISSUE TITLE
用户名显示email 前缀

### ISSUE THREAD

**Issue by swuecho** [swuecho/chat#418]
![image](https://github.com/swuecho/chat/assets/666683/608ce502-a19d-4e95-a8a6-5b0ecc91b9a9)

**Comment by swuecho** [comment]
userinfo backend store

**Comment by swuecho** [comment]
或者把这个现实去掉, 本来没什么用.

**Comment by cyx2000** [comment]
有用户名的话倒是可以展示用户名，截图的时候也可以把名称和签名加上去啥的
