### ISSUE TITLE
claude模式 fail to get session: : sql: no rows in result set

### ISSUE THREAD

**Issue by feynmam** [swuecho/chat#61]
claude模式对话返回的是fail to get session: : sql: no rows in result set

**Comment by swuecho** [comment]
这个看起来跟 claude 关系不大, 切换回open ai 报错么

**Comment by feynmam** [comment]
我之前把openai那两行删了，现在把改回来又把openai的api加上，已经正常使用了。
还有一个问题，每次开新对话都是默认chatgpt。

**Comment by swuecho** [comment]
默认的模型是chatgpt 我目前的体验 claude 还是弱一点 

以后可以考虑默认是claude
